services:

  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - sample-docker-application-network
    
  sample-docker-application:
    container_name: sample-docker-application
    image: sample-docker-application
    ports:
      - "8080:8080"
    networks:
      - sample-docker-application-network
  
volumes:
  postgres:

networks:
  sample-docker-application-network:
    driver: bridge